markdown: rdiscount
port: 4000
baseurl:    /
url: http://localhost:4000

safe: true
source: git@github.com:aprodeweb/rubyonrails.org.es.git
lsi: false
highlighter: rouge

source:      .
destination: ./_site

exclude: [vendor]
